"""added image to skus table

Revision ID: 04f97ba0796d
Revises: 2ed61e2ad7d4
Create Date: 2023-09-08 14:54:52.718324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f97ba0796d'
down_revision = '2ed61e2ad7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
