"""added sku id to orderitem table

Revision ID: 53ac72067f2f
Revises: 04f97ba0796d
Create Date: 2023-09-10 14:16:21.909041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ac72067f2f'
down_revision = '04f97ba0796d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orderitems_sku_id_skus'), 'skus', ['sku_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orderitems_sku_id_skus'), type_='foreignkey')
        batch_op.drop_column('sku_id')

    # ### end Alembic commands ###
